apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-service
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: news-service
    spec:
      containers:
        - name: news-service
          image: outoftheparkacr.azurecr.io/news-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: news-http
---
apiVersion: v1
kind: Service
metadata:
  name: news-service-deployment
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: news-service
  type: ClusterIP

